stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/dataset.csv
    params:
      - config/params.yaml:
          - data.test_size
          - data.random_state
    outs:
      - data/processed/x_test.csv
      - data/processed/y_test.csv
      - models/label_encoders.pkl
      - models/scaler.pkl
      - models/feature_columns.pkl

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/data_preprocessing.py
      - data/raw/dataset.csv
    params:
      - config/params.yaml:
          - model
          - data
    metrics:
      - models/metrics.json:
          cache: false
    outs:
      - models/best_random_forest_model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/best_random_forest_model.pkl
      - data/processed/x_test.csv
      - data/processed/y_test.csv
    metrics:
      - models/metrics.json:
          cache: false
    plots:
      - models/predictions.csv:
          x: actual
          y: predicted
