data:
  raw_data_path: "data/raw/dataset.csv"
  test_size: 0.2
  random_state: 42
  target_column: "3 Year Return"

model:
  n_estimators: [100, 200, 300]
  max_depth: [null, 5, 10]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  cv_folds: 5

mlflow:
  experiment_name: "stock_return_prediction"
  tracking_uri: "http://localhost:5000"
